import { z } from "zod";

export const SemanticTacticSchema = z.object({
  type: z.enum([
    "urgency",
    "authority",
    "fear",
    "threat",
    "false_trust",
    "helpfulness",
    "secrecy",
    "isolation",
    "scarcity",
    "reward",
    "verification_suppression",
    "channel_migration",
    "credential_request",
    "financial_pressure",
  ]),
  confidence: z.number().min(0).max(1),
  evidence: z.string().max(200).nullable().optional(),
});

export const SemanticExtractionSchema = z.object({
  context_sufficiency: z.enum(["enough", "insufficient"]),
  claimed_identity_type: z.enum([
    "government",
    "financial_institution",
    "courier",
    "employer",
    "law_enforcement",
    "platform",
    "person",
    "other",
    "unknown",
  ]),
  scam_family: z.enum([
    "delivery_scam",
    "government_impersonation",
    "law_enforcement",
    "account_verification",
    "employment_scam",
    "recovery_scam",
    "reward_claim",
    "social_engineering_opener",
    "investment_fraud",
    "romance_scam",
    "financial_phishing",
    "tech_support",
    "unknown",
  ]),
  requested_actions: z.array(z.enum([
    "click_link",
    "call_number",
    "submit_credentials",
    "pay_money",
    "reply",
    "download_app",
    "remote_access",
    "move_channel",
    "none",
    "unknown",
  ])).max(5),
  requested_assets: z.array(z.enum([
    "money",
    "password",
    "otp_or_mfa_code",
    "bank_login",
    "card_data",
    "identity_data",
    "crypto",
    "gift_card",
    "remote_device_access",
    "conversation_engagement",
    "unknown",
  ])).max(5),
  tactics: z.array(SemanticTacticSchema).max(8),
  attack_stage: z.enum([
    "initial_contact",
    "lure",
    "trust_building",
    "authority_establishment",
    "pressure_escalation",
    "credential_capture",
    "payment_extraction",
    "isolation",
    "repeat_extraction",
    "recovery",
    "unclear",
  ]),
  confidence: z.number().min(0).max(1),
});

export type SemanticExtraction = z.infer<typeof SemanticExtractionSchema>;
