"use client";
import { useRef, useState } from "react";
import { type ArchiveLang, type Pair } from "./archiveData";
import styles from "./archiveExplorer.module.css";
const p = (en: string, fr: string): Pair => ({ en, fr });
const steps = [p("Contact", "Le contact"), p("Request", "La demande"), p("Pressure", "La pression"), p("End goal", "L’objectif"), p("Your response", "Votre réponse")];
const bank = [
  { title: p("It starts with contact.", "Tout commence par un contact."), quote: p("“This is your bank’s fraud department.”", "« Ici le service des fraudes de votre banque. »"), context: p("An unexpected phone call", "Un appel inattendu"), explanation: p("A story reaches you through a call, message, email, website, advertisement or face-to-face conversation. Sometimes you make the first contact. Here, the caller claims to be someone you would normally trust.", "Une histoire vous rejoint par appel, message, courriel, site, publicité ou conversation en personne. Parfois, c’est vous qui faites le premier contact. Ici, la personne prétend être quelqu’un en qui vous auriez normalement confiance."), takeaway: p("A familiar name tells you who they claim to be. It does not establish who they are.", "Un nom familier indique l’identité revendiquée. Il ne prouve pas l’identité réelle.") },
  { title: p("The story asks you to act.", "L’histoire vous invite à agir."), quote: p("“Read me the six-digit code we just sent.”", "« Donnez-moi le code à six chiffres que nous venons d’envoyer. »"), context: p("The action they want", "Le geste demandé"), explanation: p("Look for the concrete action: click, reply, call, pay, install something or share information. In this example, the caller wants your security code. That is the request, whatever reason they give for it.", "Repérez le geste concret : cliquer, répondre, appeler, payer, installer quelque chose ou partager une information. Ici, la personne veut votre code de sécurité. C’est la demande, peu importe la raison invoquée."), takeaway: p("Separate the story from the action it asks you to take.", "Distinguez l’histoire du geste qu’on vous demande de poser.") },
  { title: p("Pressure makes the request feel necessary.", "La pression rend la demande nécessaire en apparence."), quote: p("“Someone is moving your money right now. I need the code to stop it.”", "« Quelqu’un transfère votre argent en ce moment. Il me faut le code pour l’arrêter. »"), context: p("Urgency + fear + borrowed authority", "Urgence + peur + autorité empruntée"), explanation: p("The caller uses fear of losing money and the apparent authority of a bank. Acting quickly starts to feel safer than checking. Other stories may use hope, affection, loyalty or obligation. Feeling those emotions is normal.", "La personne utilise la peur de perdre de l’argent et l’autorité apparente d’une banque. Agir vite semble plus sûr que vérifier. D’autres histoires peuvent utiliser l’espoir, l’affection, la loyauté ou l’obligation. Ces émotions sont normales."), takeaway: p("Notice what they want you to feel, and which action that feeling is meant to trigger.", "Remarquez ce qu’on veut vous faire ressentir et le geste que cette émotion doit déclencher.") },
  { title: p("The real goal sits behind the request.", "Le véritable objectif se cache derrière la demande."), quote: p("The claim: “Protect your account.”\nThe possible result: give someone access to it.", "La promesse : « Protéger votre compte. »\nLe résultat possible : donner accès à ce compte."), context: p("What they may actually obtain", "Ce qu’on peut réellement obtenir"), explanation: p("The code may help someone sign in or authorise a transaction. The end goal can be money, account access, personal information or control over what you do. Follow what the requested action makes possible.", "Le code peut aider quelqu’un à se connecter ou à autoriser une opération. L’objectif peut être votre argent, un accès, des renseignements personnels ou le contrôle de vos gestes. Regardez ce que la demande rend possible."), takeaway: p("Ask what changes hands, or who gains control, if you follow the instruction.", "Regardez ce qui change de mains, ou qui prend le contrôle, si vous suivez l’instruction.") },
  { title: p("You can step outside the story.", "Vous pouvez sortir de cette histoire."), quote: p("“I’ll contact my bank myself.”", "« Je vais joindre ma banque moi-même. »"), context: p("A response you can use", "Une réponse que vous pouvez utiliser"), explanation: p("Keep the code private. End the call and use the number on your bank card, ideally from another phone. You can also speak with someone you trust. You are checking through a contact you chose, outside the caller’s control.", "Gardez le code privé. Raccrochez et composez le numéro sur votre carte bancaire, idéalement d’un autre téléphone. Vous pouvez aussi parler à une personne de confiance. Vous vérifiez par un contact que vous avez choisi, hors du contrôle de la personne."), takeaway: p("Pause the requested action. Verify independently. Then decide.", "Suspendez le geste demandé. Vérifiez par vous-même. Puis décidez.") },
];
const parcel = [
  { title: p("A different way to reach you.", "Une autre façon de vous rejoindre."), quote: p("“Your parcel could not be delivered.”", "« Votre colis n’a pas pu être livré. »"), context: p("An unexpected delivery text", "Un texto de livraison inattendu"), explanation: p("This time, the story arrives by text and borrows a delivery company’s identity. It can feel believable when you are already expecting a package.", "Cette fois, l’histoire arrive par texto et emprunte l’identité d’un transporteur. Elle peut sembler crédible si vous attendez déjà un colis."), takeaway: p("Recognising a familiar situation is not the same as verifying its sender.", "Reconnaître une situation familière ne suffit pas à vérifier l’expéditeur.") },
  { title: p("A small payment, through their link.", "Un petit paiement, par leur lien."), quote: p("“Pay the $2.17 fee using this link.”", "« Payez les frais de 2,17 $ par ce lien. »"), context: p("The action they want", "Le geste demandé"), explanation: p("The request moves you to a page the sender chose. Even a small fee can lead to a form asking for card information or other personal details.", "La demande vous déplace vers une page choisie par l’expéditeur. Même de petits frais peuvent mener à un formulaire demandant vos renseignements de carte ou d’autres détails personnels."), takeaway: p("Look at the information and access being requested, not only the price.", "Regardez les informations et les accès demandés, pas seulement le prix.") },
  { title: p("The deadline pushes you forward.", "L’échéance vous pousse à agir."), quote: p("“Pay within an hour or your parcel will be returned.”", "« Payez dans l’heure, sinon votre colis sera retourné. »"), context: p("Urgency + a threatened inconvenience", "Urgence + inconvénient annoncé"), explanation: p("The message makes a routine inconvenience feel immediate. The small amount can make checking seem unnecessary. It is another route to acting before verifying.", "Le message rend un inconvénient banal urgent. Le petit montant peut faire paraître la vérification inutile. C’est une autre façon de vous faire agir avant de vérifier."), takeaway: p("A deadline does not prove that a request is genuine.", "Une échéance ne prouve pas qu’une demande est légitime.") },
  { title: p("The fee may be only the opening.", "Les frais peuvent n’être que le début."), quote: p("The claim: “Release your parcel.”\nThe possible result: collect your payment details.", "La promesse : « Libérer votre colis. »\nLe résultat possible : recueillir vos renseignements de paiement."), context: p("What they may actually obtain", "Ce qu’on peut réellement obtenir"), explanation: p("The goal may be the payment itself, your card details or information for another attempt. The promised delivery gives a reason to ask for them.", "L’objectif peut être le paiement, vos renseignements de carte ou des informations pour une autre tentative. La livraison promise donne une raison de les demander."), takeaway: p("Follow what you would hand over to get the promised result.", "Regardez ce que vous céderiez pour obtenir le résultat promis.") },
  { title: p("Check through a channel you choose.", "Vérifiez par un contact que vous choisissez."), quote: p("Open the delivery company’s app yourself.", "Ouvrez vous-même l’application du transporteur."), context: p("A response you can use", "Une réponse que vous pouvez utiliser"), explanation: p("Leave the message’s link alone. Use the carrier’s known app or find its website independently, then check your delivery there. The sender no longer controls the place where you verify the story.", "Laissez le lien du message de côté. Utilisez l’application connue du transporteur ou trouvez son site par vous-même, puis vérifiez votre livraison. L’expéditeur ne contrôle plus l’endroit où vous vérifiez l’histoire."), takeaway: p("Different story. Same useful response: verify independently.", "Une autre histoire. Le même réflexe utile : vérifier par vous-même.") },
];

export default function ScamGuide({ lang, onExplore }: { lang: ArchiveLang; onExplore: () => void }) {
  const tr = (en: string, fr: string) => lang === "fr" ? fr : en;
  const [step, setStep] = useState(0);
  const [scenario, setScenario] = useState<"bank" | "parcel">("bank");
  const title = useRef<HTMLHeadingElement>(null);
  const content = scenario === "bank" ? bank : parcel;
  const complete = step === steps.length;
  const current = content[Math.min(step, steps.length - 1)];
  const move = (next: number) => {
    setStep(next);
    requestAnimationFrame(() => {
      title.current?.focus({ preventScroll: true });
      title.current?.scrollIntoView({ block: "center", behavior: "instant" });
    });
  };
  return <section className={styles.simpleGuide} aria-label={tr("How a scam unfolds", "Comment une fraude se déroule")}>
    <header className={styles.guideHeader}><span className={styles.eyebrow}>{tr("A short guide", "Un court guide")}</span><span>{complete ? tr("The whole pattern", "Le stratagème complet") : tr(`Step ${step + 1} of 5`, `Étape ${step + 1} sur 5`)}</span></header>
    <nav className={styles.guideSteps} aria-label={tr("Guide steps", "Étapes du guide")}>{steps.map((label, index) => <button key={index} onClick={() => move(index)} aria-current={step === index ? "step" : undefined}><span>{index + 1}</span>{label[lang]}</button>)}</nav>
    {!complete ? <div className={styles.guideBody}>
      <div className={styles.guideExample}><p className={styles.eyebrow}>{tr("Follow the example", "Suivez l’exemple")}</p><blockquote>{current.quote[lang]}</blockquote><span>{current.context[lang]}</span><small>{tr("Illustrative scenario — no private message is shown.", "Scénario fictif — aucun message privé n’est affiché.")}</small></div>
      <div className={styles.guideExplanation}><h2 ref={title} tabIndex={-1}>{current.title[lang]}</h2><p>{current.explanation[lang]}</p><div className={styles.remember}><b>{tr("The thing to notice", "Le point à retenir")}</b><p>{current.takeaway[lang]}</p></div><div className={styles.lessonActions}>{step > 0 && <button className={styles.back} onClick={() => move(step - 1)}>{tr("Previous", "Précédent")}</button>}<button className={styles.primary} onClick={() => move(step + 1)}>{step < 4 ? tr("Next:", "Ensuite :") + " " + steps[step + 1][lang].toLowerCase() : tr("See the whole pattern", "Voir le stratagème complet")} <span aria-hidden="true">→</span></button></div></div>
    </div> : <div className={styles.guideRecap}><p className={styles.eyebrow}>{tr("Put the pieces together", "Rassemblez les éléments")}</p><h2 ref={title} tabIndex={-1}>{tr("You can follow the pattern now.", "Vous pouvez maintenant suivre le stratagème.")}</h2><p>{tr("Use these five points to look at a new situation. A warning sign is a reason to check; it is not proof on its own.", "Utilisez ces cinq points pour examiner une nouvelle situation. Un indice justifie une vérification; il ne constitue pas une preuve à lui seul.")}</p><ol>{content.map((item, i) => <li key={i}><span>{i + 1}</span><div><b>{steps[i][lang]}</b><p>{item.quote[lang]}</p></div></li>)}</ol><div className={styles.recapActions}><button className={styles.primary} onClick={onExplore}>{tr("Explore more patterns", "Explorer d’autres stratagèmes")} <span aria-hidden="true">→</span></button><button className={styles.secondary} onClick={() => { setScenario(scenario === "bank" ? "parcel" : "bank"); move(0); }}>{scenario === "bank" ? tr("See a delivery-message example", "Voir un exemple de texto de livraison") : tr("See the bank-call example", "Voir l’exemple d’appel bancaire")}</button></div></div>}
    <p className={styles.lessonSource}>{tr("Further guidance:", "Pour en savoir plus :")} <a href={lang === "fr" ? "https://antifraudcentre-centreantifraude.ca/protect-protegez-fra.htm" : "https://antifraudcentre-centreantifraude.ca/protect-protegez-eng.htm"} target="_blank" rel="noreferrer">{tr("Canadian Anti-Fraud Centre", "Centre antifraude du Canada")} ↗</a></p>
  </section>;
}
